name: testing workflows

on:
  push:
    branches: [ master ] # Pastikan nama branch sesuai!

jobs:
  greeting:
    runs-on: self-hosted

    steps:
    - name: Say Hello
    run: echo "Hello, World! üëã"

    - name: Show Date and Time
    run: echo "Current time is $(date) ‚è±Ô∏è"

    - name: Show GitHub Info
    run: |
      echo "Repository: ${{ github.repository }}"
      echo "Branch: ${{ github.ref }}"
      echo "Commit: ${{ github